# Generated by Django 4.1.3 on 2022-11-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vianda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infosolicitudvianda',
            name='itemsincluir',
        ),
        migrations.AddField(
            model_name='infosolicitudvianda',
            name='itemsincluir',
            field=models.ManyToManyField(to='vianda.itemvianda'),
        ),
    ]
