# Generated by Django 4.1.3 on 2022-11-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vianda', '0004_alter_infosolicitudvianda_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosolicitudvianda',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
