# Generated by Django 4.1.3 on 2022-11-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vianda', '0006_remove_infosolicitudvianda_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosolicitudvianda',
            name='estadoVianda',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Confirmado'), (3, 'Cancelado')], default=1),
        ),
    ]
