# Generated by Django 4.1.3 on 2022-11-07 23:16

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vianda', '0007_alter_infosolicitudvianda_estadovianda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosolicitudvianda',
            name='usuario',
            field=models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
