# Generated by Django 4.1.3 on 2022-11-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vianda', '0009_alter_infosolicitudvianda_fechainiciovianda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosolicitudvianda',
            name='fechaInicioVianda',
            field=models.DateField(),
        ),
    ]
